version: '3'

services:

  backend:
    build: polldle-backend/
    image: mickaelbaron/polldle-backend
    environment: 
      KUMULUZEE_SERVER_HTTP_PORT: 9991
    ports:
      - "9991:9991"
    networks:
      - polldlenetwork

  frontend:
    build: polldle-vue/
    image: mickaelbaron/polldle-vue
    networks:
      - polldlenetwork

  rp:
    build: polldle-rp/
    image: mickaelbaron/polldle-rp
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    networks:
      - polldlenetwork

networks:
  polldlenetwork:
